Skip RobotFramework tests on aarch64
because of:
OSError: [Errno 8] Exec format error: '/opt/circleci/.pyenv/versions/3.11.1/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager'

This is tested on x86_64 anyway!