Upgrade pip and setuptools inside Docker image
because that may lead to errors from other packages which sometimes
are not easy to see (e.g. if pip falls back to an older version).

Right now we have:
ERROR: markdown 3.1 has requirement setuptools>=36, but you'll
       have setuptools 28.8.0 which is incompatible.

which despite being reported as error doesn't seem to break anything.